# Generated by Django 5.2.4 on 2025-08-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_status',
            field=models.CharField(blank=True, default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='points_balance',
            field=models.CharField(blank=True, default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='usd_balance',
            field=models.CharField(blank=True, default='0', max_length=10),
        ),
    ]
