# Generated by Django 5.2.4 on 2025-08-15 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_profile_account_status_profile_points_balance_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
