# Generated by Django 5.2.4 on 2025-08-15 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notifications',
            field=models.TextField(blank=True, default=''),
        ),
    ]
