# Generated by Django 5.2.4 on 2025-08-15 01:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(max_length=50)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(max_length=150)),
                ('media_file', models.FileField(upload_to='uploads/videos/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
