# Generated by Django 5.2.4 on 2025-08-15 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_withdrawal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='account_details',
            field=models.CharField(max_length=100),
        ),
    ]
